### PR TITLE
[WIP] GQ-CNN 1.0

### PR DESCRIPTION
**Pull request by visatish**
Not sure if we want to merge into merge-jeff first or directly stage to master (doesn't really make sense to merge there). The concern with the latter is that we will get merge artifacts (ex. extraneous files that were deleted in release-prep) if we aren't careful. It doesn't seem that any changes were made on merge-jeff after we branched, so it should be okay.

Final TODOs:
- Update `scripts/downloads/datasets/download_dex-net_4.0_*`
- Review https://github.com/BerkeleyAutomation/gqcnn/commit/a77165554951fcfe1422080b7f76cd13d303d237#comments

### CODE REVIEW

**Comment by jeffmahler** [comment]
@visatish Finally getting around to this. I commented on the download and I'm splitting and uploading the dataset files now.

**Comment by visatish** [comment]
@jeffmahler Yeah, the one downside I see about having the automatic download with installation is that if you end up running the installation multiple times because of issues, it will keep on trying to download everything haha.

Also, can you update the dataset download scripts with the upload links? Or if you send them to me, I can do that too.

**Comment by jeffmahler** [comment]
@vsatish Actually I'd like to leave the auto-download because it's convenient. I think that we should modify them to only download the files if they don't exist.

I will update the download scripts once I upload the data.

**Comment by visatish** [comment]
> @vsatish Actually I'd like to leave the auto-download because it's convenient. I think that we should modify them to only download the files if they don't exist.
> 
> I will update the download scripts once I upload the data.

@jeffmahler Fixed.

**Comment by jeffmahler** [comment]
@visatish I think we're good to go. Just added the Dex-Net 4.0 download script.

Anything else on your end?

**Comment by visatish** [comment]
> @visatish I think we're good to go. Just added the Dex-Net 4.0 download script.
> 
> Anything else on your end?

Nope, I think this is good to go!

**Comment by visatish** [comment]
@jeffmahler Actually, let me check all the downloads first.

**Pull request merged**
